services:
  api:
    build: .
    container_name: cloudops-api
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: cloudops-postgres
    environment:
      POSTGRES_USER: cloudops_user
      POSTGRES_PASSWORD: monitor@2030
      POSTGRES_DB: cloudops_monitoring
    ports:
      - "5432:5432"
